name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: johnwesonga/go-http-server

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    # Set up Go (optional, for tests)
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.3'
        
    # Run tests (optional but recommended)
    - name: Run tests
      run: go test ./...
      
    - name: Build and push the Docker image
      run: |
        IMAGE_TAG=${GITHUB_SHA::7}
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
